export const data = [
  { id: '1',
    title: 'Bookie-shades',
    description: 'Bookie are always related to some sort of glasses',
    url: 'glass',
    votes: Math.ceil(Math.random()),
    submitter_avatar_url:'../images/avatars/bookie.jpeg',
    product_image_url:'../images/product/glass.JPG',
  },
  { id: '2',
    title: 'Makoko Heels',
    description: 'Heels for sale',
    url: 'heels',
    votes: Math.ceil(Math.random()),
    submitter_avatar_url:'./images/avatars/yaki.jpeg',
    product_image_url:'./images/product/heels.jpeg',
  },
  { id:'3',
    title: 'Black Moimoi',
    description: 'I love heels so badly',
    url: 'heelz',
    votes: Math.ceil(Math.random()),
    submitter_avatar_url:'./images/avatars/yaki.jpeg',
    product_image_url:'./images/product/heelz.jpeg',
  },
  { id:'4',
    title: 'Nerdie Stuff',
    description: 'We nerds know a bit about skating boots.',
    url: 'skate',
    votes: Math.ceil(Math.random()),
    submitter_avatar_url:'./images/avatars/nerd.jpeg',
    product_image_url:'./images/product/skate.jpeg',
  },
];
